### ISSUE TITLE
Error LZ4_decompress_safe: fffffff9 (expected    c29f0)

### ISSUE THREAD

**Issue by YuriSizuku** [shuffle2/nx2elf#10]
I try to convert game KandaAliceMoSuiriSuru which title id is 01003BD013E30000.
The error Error LZ4_decompress_safe: fffffff9 (expected    c29f0) occured.
I attached the main file here  (rename the main.txt to main). Please check it.

[main.txt](https://github.com/shuffle2/nx2elf/files/6969886/main.txt)

**Comment by shuffle2** [comment]
i think either your file is corrupted or nintendo's lz4 deviates from the mainline one in some way. Unfortunately I don't really have the time to look into it.
