### ISSUE TITLE
failed to make shdr for st_shndx 26

### ISSUE THREAD

**Issue by mophawka** [shuffle2/nx2elf#14]
./nx2elf.exe /f/tmp/exefs/main.nso output.elf
/f/tmp/exefs/main.nso:
gnu_build_id: e5d10e503f5876ea2affc3d1b916a798934db63a000000000000000000000000
         file off file len mem off  mem len  bss/algn
0 [r-x]:      101   71779a        0   cdd230      100
1 [r--]:   71789b   256c20   cde000   5220b4        1
2 [rw-]:   96e4bb     c434  1201000    df988    72678
.rodata-relative:
  .dynstr:   1eb348     8fc6
  .dynsym:   1e56c0     5c88
segment digests:
0 [r-x]: 9600edbf64377cf4e150f145a6591a0c6f2b68ac480f36c1a268114103f14f71
1 [r--]: a3e5301e5abde6710ba1e30fe95e4b3f72cf88e42f5338f489a81c5adf70a639
2 [rw-]: a73d064a74e270a6d1e8605954c8e49723cc8ec43516d580b25718eba4c1c7e2
failed to make shdr for st_shndx 26

The resulting elf file has errors when loading in IDA 9

Thanks for any help

**Comment by fm360** [comment]
im also getting the same error for a different game. lmk how this was fixed if possible

**Comment by shuffle2** [comment]
i dont remember, can you send me the elf

**Comment by fm360** [comment]
Here is my main.elf
https://drive.google.com/file/d/1ViLEkpn9fRIj2Fv_dnGZjHoJilRenOWC/view?usp=drive_link

**Comment by shuffle2** [comment]
@fm360 sorry, i meant to request the nso (the input file)...can you send that instead

**Comment by fm360** [comment]
> [@fm360](https://github.com/fm360) sorry, i meant to request the nso (the input file)...can you send that instead

https://drive.google.com/file/d/1r2Ai94tls1711J41akvJSemxQQ32tcXA/view?usp=drive_link

**Comment by shuffle2** [comment]
at least in your case, the issue is that there's a symbol just off the end off bss,
in .dynsym, it's here:
```
1167: 00000000078d4000     0 NOTYPE  GLOBAL DEFAULT   26 end
```

If i just allow it, ida shows:
```
.prgend:00000000078D4000 _end
```

so for now, i'll just allow this edge case (probably should actually be looked into, but 🤷‍♂️)

**Comment by shuffle2** [comment]
https://github.com/shuffle2/nx2elf/commit/8abc2d5af5d39dd5d9a317776497b56c14b7327f
