### ISSUE TITLE
make on raspberry fails (my only linux machine)

### ISSUE THREAD

**Issue by GizmoTheGreen** [shuffle2/nx2elf#3]
pi@raspberrypi:~/nx2elf $ make
g++ -o nx2elf *.cpp *.c -lstdc++fs -std=c++14
nx2elf.cpp: In member function ‘bool NsoFile::WriteElf(const std::experimental::                                                            filesystem::v1::__cxx11::path&)’:
nx2elf.cpp:723:117: error: no matching function for call to ‘ElfEHInfo::MeasureF                                                            rame(eh_frame_hdr*, uintptr_t*, u64*)’
 _frame_hdr *>(&image[eh_info.hdr_addr]), &eh_frame_ptr, &eh_info.frame_size)) {
                                                                            ^
In file included from nx2elf.cpp:12:0:
elf_eh.h:37:7: note: candidate: bool ElfEHInfo::MeasureFrame(const eh_frame_hdr*                                                            , uintptr_t*, size_t*)
  bool MeasureFrame(const eh_frame_hdr *hdr, uintptr_t *eh_frame_ptr, size_t *eh                                                            _frame_len);
       ^~~~~~~~~~~~
elf_eh.h:37:7: note:   no known conversion for argument 3 from ‘u64* {aka long l                                                            ong unsigned int*}’ to ‘size_t* {aka unsigned int*}’
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 1

is it related to the arm architecture or?

**Comment by shuffle2** [comment]
the current code expects 64bit
