### ISSUE TITLE
"please report this" triggered on Fire emblem: three houses

### ISSUE THREAD

**Issue by ampheul** [shuffle2/nx2elf#6]
Filing in response to

```
error: raw MOD failed to find .data in .dynsym. please report this.
```

---
I am trying to look into the code for fire emblem three houses using your tool.
Here is the process I went through:

First applying nx2elf to `main` directly I get the following failure and no output.
```
../hfk10miiu03lobmh/main:
gnu_build_id: cecf500cea4c214c46abd94d133939c400000000000000000000000000000000
         file off file len mem off  mem len  bss/algn
0 [r-x]:      101   623532        0   a917c0      100
1 [r--]:   623633   3273c4   a92000   e14840        1
2 [rw-]:   94a9f7     9b10  18a7000    cc0e0   72cf20
.rodata-relative:
  .dynstr:   1a41f8     5e56
  .dynsym:   1a0be0     3618
segment digests:
0 [r-x]: 4aecae5756a817df37200b8c249a28a24f30acd3e920ec27b667e69cd1a4a771
1 [r--]: 075456fdfd6b5c68d81d1a844314d5a07072a4c2e425d8a41c9f08eb4c00c377
2 [rw-]: 05c8119381258163d3ac052d1dccc82ffdc63daca8c7625630050f73b80cc8ff
failed to make shdr for st_shndx 22
```

I had success getting an output using nso.py from SciresM however (https://gist.github.com/SciresM/62715cfb5d06648ee46bc4622d2725e5) 
```
python2 nso.py main output
```
so I tried running nx2elf on the output.
Triggering:

```
error: raw MOD failed to find .data in .dynsym. please report this.
```

As you have requested, here is the report.

**Comment by shuffle2** [comment]
The "please report this" message is only intended for actual MOD files, not things which have been processed in some way.

I got the fire emblem three houses `main` file with md5 digest `6734dbdc930431d28c8d6b487134f2a1`. This has the same header as yours. nx2elf produces a `main.elf` file for me. Are you sure it's not producing an elf for you? If it's not, try moving the `main` file somewhere with a short and simple ASCII-only directory path, and see if it works then. Let me know.

**Comment by ampheul** [comment]
Ah, it does seem to generate the main.elf file, I feel so dumb now.

Yesterday I am pretty sure there was no main.elf. I combed over the files and even invoked `find . -name "*.elf"` returning nothing. However I am using WSL and it is possible that this causes unexpected behaviour.
