### ISSUE TITLE
please help to solve this problem

### ISSUE THREAD

**Issue by zellfy** [shuffle2/nx2elf#7]
please check this file, I can't exchange it to elf, thank you.

https://drive.google.com/open?id=15NpZo3zIehp6PF7dbDS5E0FLqlP_pgZu

**Comment by shuffle2** [comment]
It should be fixed (at least output elf) with https://github.com/shuffle2/nx2elf/commit/7212e82a77b84fcc18ef2d050970350dbf63649b
